# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ESE-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ESE-App
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  
  target 'ESE-AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ESE-AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
